application:
  config:
    domain-detect:
      enable: true
      timeout: 3000
      concurrency: 128
      provider:
        - 1.1.1.1
        - 8.8.8.8

    exclude:
      # å±è”½æ­¤åŸŸä¼šå¯¼è‡´Edgeæµè§ˆå™¨ç¿»è¯‘ä¸å¯ç”¨
      - "edge.microsoft.com"
      # å±è”½æ­¤åŸŸä¼šå¯¼è‡´å°ç±³å¤©æ°”ç½‘ç»œå¼‚å¸¸
      - "metok.sys.miui.com"
      # å±è”½æ­¤åŸŸä¼šå¯¼è‡´10086 Appç™»é™†å¼‚å¸¸
      - "client.app.coc.10086.cn"
      # å±è”½æ­¤åŸŸä¼šå¯¼è‡´MSNé¡µé¢æ— æ³•æ­£å¸¸åŠ è½½
      - "assets.msn.com"

  # è§„åˆ™æºé…ç½®
  # remoteä¸ºè¿œç¨‹è§„åˆ™ï¼Œlocalä¸ºæœ¬åœ°è§„åˆ™ï¼Œæ”¯æŒå¤šä¸ªè§„åˆ™æº
  rule:
    remote:
      - name: AdGuard Cookieé€šçŸ¥è¿‡æ»¤å™¨
        path: https://filters.adtidy.org/android/filters/18_optimized.txt
        type: easylist

      - name: AdGuard å¼¹çª—è¿‡æ»¤å™¨
        path: https://filters.adtidy.org/android/filters/19_optimized.txt
        type: easylist

      - name: AdGuard ç§»åŠ¨æ‹¦æˆªç¨‹åºæ¨ªå¹…å¹¿å‘Šçš„è¿‡æ»¤å™¨
        path: https://filters.adtidy.org/android/filters/20_optimized.txt
        type: easylist

      - name: AdGuard å…¶ä»–æ¼äººå¹¿å‘Šè¿‡æ»¤å™¨
        path: https://filters.adtidy.org/android/filters/21_optimized.txt
        type: easylist

      - name: AdGuard æ¼äººå¹¿å‘Šè¿‡æ»¤å™¨
        path: https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_14_Annoyances/filter.txt
        type: easylist

      - name: Online Malicious URL Blocklist
        path: https://urlhaus-filter.pages.dev/urlhaus-filter-ag-online.txt
        type: easylist

      - name: AdGuard å°å·¥å…·è¿‡æ»¤å™¨
        path: https://filters.adtidy.org/android/filters/22_optimized.txt
        type: easylist

      - name: ABP åå¹¿å‘Šè¿‡æ»¤
        path: https://easylist-downloads.adblockplus.org/abp-filters-anti-cv.txt

      - name: xndeye adblock list of easylist
        path: https://raw.githubusercontent.com/xndeye/adblock_list/refs/heads/release/easylist.txt
   
      - name: TTæ‹’ç»åˆ—è¡¨
        path: https://ghproxy.net/https://raw.githubusercontent.com/TTDNS/Cat/refs/heads/main/TT%E6%8B%92%E7%BB%9D%E5%88%97%E8%A1%A8%E6%B8%85%E5%8D%95%20(%E6%9B%B4%E6%96%B0%E4%B8%AD).txt
  
      - name: AdGuard Tracking Protection filter (Optimized)
        path: https://filters.adtidy.org/android/filters/3_optimized.txt
        type: easylist
 
      - name: Bypass Paywalls Clean filter
        path: https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt

      - name: æ™´é›…å¹¿å‘Šæ‹¦æˆªè§„åˆ™é‡ç½®ç‰ˆæ”¯æŒIOS
        path: http://rssv.cn/adguard/api.php?type=black
      
      - name: HyperADRules
        path: https://raw.githubusercontent.com/Lynricsy/HyperADRules/master/rules.txt

      - name: DD-AD
        path: https://raw.githubusercontent.com/afwfv/DD-AD/refs/heads/release/DD-AD.txt

      - name: å»å¹¿å‘Šè§„åˆ™ï¼Œé…·å®‰åé¦ˆåé¦ˆ
        path: https://raw.githubusercontent.com/qq5460168/666/refs/heads/master/rules.txt
        
      - name: AdRules æ©˜çŒ«
        path: https://adrules.5iclub.us.kg/adblock.txt
    
      - name: NEO DEV HOST
        path: https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker

      - name: jiekouAD
        path: https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt

      - name: DNS-Kuner
        path: https://raw.githubusercontent.com/Kuner-mw/DNS-Kuner/main/FilterRules/blacklist.txt 
        
      - name: å»å¹¿å‘Šè§„åˆ™ï¼Œåé¦ˆğŸ§ç¾¤è¯·ç‚¹å‡»ä¸»é¡µ
        path: https://raw.githubusercontent.com/qq5460168/dangchu/main/black.txt

      - name: SMå¹¿å‘Šä¸Ÿé‚£å—hosts
        path: https://raw.githubusercontent.com/2Gardon/SM-Ad-FuckU-hosts/refs/heads/master/SMAdHosts
 
      - name: HaGeZi's Pro DNS Blocklist
        path: https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/pro.txt

      - name: 1Hosts (Lite)
        path: https://raw.githubusercontent.com/badmojr/1Hosts/refs/heads/master/Lite/adblock.txt
        
      - name: JiuYue_Rules
        path: https://rules.vlo.cc/dns/dns.txt    

      - name: DNS-Kuner Allow
        path: https://raw.githubusercontent.com/Kuner-mw/DNS-Kuner/main/FilterRules/allowlist.txt
      
      - name: AdguardFilteræ ‡å‡†
        path: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/rule.txt

      - name: AdguardFilteré»‘åå•
        path: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/bad_apple.txt
        
      - name: AdguardFilterç™½åå•
        path: https://raw.githubusercontent.com/miaoermua/AdguardFilter/main/whitelist.txt
        
  output:
    file_header: |
      Title: wiz adblock list of ${type}
      Last Modified: ${date}
      Homepage: https://github.com/ALLOVERleng/ad-filters-subscriber
    
    files:
      - name: easylist.txt
        type: easylist
        filter:
          - basic
          - wildcard
          - unknown

      - name: dns.txt
        type: easylist
        file_header: |
          Title: wiz adblock list of dns 
          Last Modified: ${date}
        filter:
          - basic
          - wildcard

      - name: modify.txt
        type: easylist
        filter:
          - unknown

      - name: dnsmasq.conf
        type: dnsmasq

      - name: clash.yaml
        type: clash

      - name: smartdns.conf
        type: smartdns

      - name: hosts
        type: hosts
# å‚è€ƒ `application-example.yaml` å¹¶åœ¨å¤„æ·»åŠ è®¢é˜…è§„åˆ™ï¼Œè¯·æ³¨æ„ç¼©è¿›
# Refer to `application-example.yaml` and add subscription rules thereï¼Œplease note the indentation
